#pragma once
namespace hfPosition_t {
	enum videoPosition {
		HF_UPPER_LEFT,
		HF_UPPER_RIGHT,
		HF_CENTER_LEFT,
		HF_CENTER_RIGHT,
		HF_LOWER_LEFT,
		HF_LOWER_RIGHT,
		HF_UPPER_THIRD,
		HF_CENTER_THIRD,
		HF_LOWER_THIRD,
		HF_LEFT_HALF,
		HF_RIGHT_HALF,
		HF_FULL_SCREEN
	};
}
